import { useState } from 'react'
import Image from 'next/image'
import { Box, type BoxProps, type SystemStyleObject } from '@chakra-ui/react'

export type BackdropOverlays = NonNullable<BoxProps['bgImage']>[]

const TOP_BAND_FADE = 'linear-gradient(to bottom, rgba(20,24,28,0.35) 0%, rgba(20,24,28,0.55) 55%, #14181c 100%)'
const TOP_BAND_VIGNETTE = 'radial-gradient(ellipse 120% 100% at 50% 0%, transparent 40%, rgba(20,24,28,0.9) 100%)'
const VIEWPORT_VIGNETTE = 'radial-gradient(circle, transparent 20%, #14181c 90%)'
const HERO_BOTTOM_FADE = {
  base: 'linear-gradient(to top, #14181c 0%, #14181c 10%, rgba(20,24,28,0.35) 60%, rgba(20,24,28,0.85) 100%)',
  md: 'linear-gradient(to bottom, rgba(20,24,28,0.35) 0%, rgba(20,24,28,0.8) 60%, #14181c 100%)'
}
const SIDE_VIGNETTE = 'linear-gradient(to right, #14181c 0%, transparent 20%, transparent 80%, #14181c 100%)'

// Single source of truth for backdrop gradients — pass a custom `overlays`
// array to restyle, but keep it here so all backdrops stay consistent.
export const BACKDROP_OVERLAYS = {
  topBand: [TOP_BAND_FADE, TOP_BAND_VIGNETTE],
  viewport: [VIEWPORT_VIGNETTE],
  detailHero: [HERO_BOTTOM_FADE, SIDE_VIGNETTE]
} satisfies Record<string, BackdropOverlays>

// Local art rendered when `path` is absent/fails — generated by
// scripts/generate-backdrop-fallback.js.
export const BACKDROP_FALLBACKS = {
  galaxy: {
    src: '/backdrop_fallback_lg.webp',
    srcSet: '/backdrop_fallback.webp 1376w, /backdrop_fallback_lg.webp 2560w'
  }
} satisfies Record<string, { src: string; srcSet: string }>

interface BackdropProps extends Omit<BoxProps, 'children'> {
  /** TMDB backdrop path (or full URL); null/undefined renders the fallback art */
  path?: string | null
  alt?: string
  overlays?: BackdropOverlays
  /** Which local art to show when there's no usable `path` */
  fallback?: keyof typeof BACKDROP_FALLBACKS
  imagePosition?: SystemStyleObject['objectPosition']
  imageMask?: SystemStyleObject['maskImage']
  imageSizes?: string
  priority?: boolean
}

export default function Backdrop({
  path,
  alt = '',
  overlays = BACKDROP_OVERLAYS.topBand,
  fallback = 'galaxy',
  imagePosition = 'center 20%',
  imageMask,
  imageSizes = '100vw',
  priority = false,
  ...rest
}: BackdropProps) {
  const [failed, setFailed] = useState(false)
  const [loaded, setLoaded] = useState(false)
  const [swapped, setSwapped] = useState(false)
  const [prevPath, setPrevPath] = useState(path)
  // Browsers keep painting the old <img> frame until the new src decodes, so
  // after a path change we hide the image until its onLoad — otherwise the
  // previous title's backdrop flashes on hover swaps and detail-page nav.
  if (prevPath !== path) {
    setPrevPath(path)
    setFailed(false)
    setLoaded(false)
    setSwapped(true)
  }
  const fallbackArt = BACKDROP_FALLBACKS[fallback]
  const imgOpacity = swapped && !loaded ? 0 : 1
  const onImgLoad = () => setLoaded(true)

  return (
    <Box position='absolute' top={0} right={0} bottom={0} left={0} overflow='hidden' pointerEvents='none' {...rest}>
      <Box
        position='absolute'
        inset={0}
        css={{
          '& img': {
            objectFit: 'cover',
            objectPosition: imagePosition,
            WebkitMaskImage: imageMask,
            maskImage: imageMask
          }
        }}
      >
        {path && !failed ? (
          <Image
            src={path}
            alt={alt}
            fill
            priority={priority}
            sizes={imageSizes}
            onLoad={onImgLoad}
            onError={() => setFailed(true)}
            style={{
              opacity: imgOpacity,
              transition: 'opacity 0.25s ease-in'
            }}
          />
        ) : (
          // eslint-disable-next-line @next/next/no-img-element -- raw srcSet fallback; next/image can't emit this markup
          <img
            src={fallbackArt.src}
            srcSet={fallbackArt.srcSet}
            sizes='100vw'
            alt={alt}
            fetchPriority={priority ? 'high' : 'auto'}
            onLoad={onImgLoad}
            style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', opacity: imgOpacity, transition: 'opacity 0.25s ease-in' }}
          />
        )}
      </Box>
      {overlays.map((overlay, i) => (
        <Box key={i} position='absolute' inset={0} bgImage={overlay} />
      ))}
    </Box>
  )
}

