// Keyword-informed backlog for the content pipeline. Volumes/KD from OpenSEO
// research (US, Oct 2026). `similar` seeds resolve movieTitle via TMDB search and
// power "Movies Like X" pages off /movie/{id}/recommendations. `discover` seeds
// hand the keyword + hint to the generator, which drafts TMDB discover params.
export const topicSeeds = [
  { slug: 'movies-like-interstellar', keyword: 'movies like interstellar', type: 'similar', movieTitle: 'Interstellar' },
  { slug: 'movies-like-the-notebook', keyword: 'movies like the notebook', type: 'similar', movieTitle: 'The Notebook' },
  { slug: 'movies-like-the-hunger-games', keyword: 'movies like the hunger games', type: 'similar', movieTitle: 'The Hunger Games' },
  { slug: 'movies-like-superbad', keyword: 'movies like superbad', type: 'similar', movieTitle: 'Superbad' },
  { slug: 'movies-like-shutter-island', keyword: 'movies like shutter island', type: 'similar', movieTitle: 'Shutter Island' },
  { slug: 'movies-like-knives-out', keyword: 'movies like knives out', type: 'similar', movieTitle: 'Knives Out' },
  { slug: 'movies-like-coraline', keyword: 'movies like coraline', type: 'similar', movieTitle: 'Coraline' },
  { slug: 'movies-like-maze-runner', keyword: 'movies like maze runner', type: 'similar', movieTitle: 'The Maze Runner' },
  { slug: 'movies-like-good-will-hunting', keyword: 'movies like good will hunting', type: 'similar', movieTitle: 'Good Will Hunting' },
  { slug: 'movies-like-10-things-i-hate-about-you', keyword: 'movies like 10 things i hate about you', type: 'similar', movieTitle: '10 Things I Hate About You' },
  { slug: 'movies-like-white-chicks', keyword: 'movies like white chicks', type: 'similar', movieTitle: 'White Chicks' },
  { slug: 'movies-like-the-hangover', keyword: 'movies like the hangover', type: 'similar', movieTitle: 'The Hangover' },
  { slug: 'movies-like-inception', keyword: 'movies like inception', type: 'similar', movieTitle: 'Inception' },
  { slug: 'movies-like-harry-potter', keyword: 'movies like harry potter', type: 'similar', movieTitle: "Harry Potter and the Philosopher's Stone" },
  { slug: 'movies-like-the-devil-wears-prada', keyword: 'movies like the devil wears prada', type: 'similar', movieTitle: 'The Devil Wears Prada' },
  { slug: 'movies-like-get-out', keyword: 'movies like get out', type: 'similar', movieTitle: 'Get Out' },
  { slug: 'movies-like-the-conjuring', keyword: 'movies like the conjuring', type: 'similar', movieTitle: 'The Conjuring' },
  { slug: 'movies-like-twilight', keyword: 'movies like twilight', type: 'similar', movieTitle: 'Twilight' },
  { slug: 'movies-like-pride-and-prejudice', keyword: 'movies like pride and prejudice', type: 'similar', movieTitle: 'Pride & Prejudice' },
  { slug: 'movies-like-legally-blonde', keyword: 'movies like legally blonde', type: 'similar', movieTitle: 'Legally Blonde' },
  { slug: 'movies-like-fight-club', keyword: 'movies like fight club', type: 'similar', movieTitle: 'Fight Club' },
  { slug: 'movies-like-john-wick', keyword: 'movies like john wick', type: 'similar', movieTitle: 'John Wick' },
  { slug: 'movies-like-national-treasure', keyword: 'movies like national treasure', type: 'similar', movieTitle: 'National Treasure' },
  { slug: 'movies-like-midsommar', keyword: 'movies like midsommar', type: 'similar', movieTitle: 'Midsommar' },
  { slug: 'movies-like-scream', keyword: 'movies like scream', type: 'similar', movieTitle: 'Scream' },
  { slug: 'movies-like-prisoners', keyword: 'movies like prisoners', type: 'similar', movieTitle: 'Prisoners' },
  { slug: 'movies-like-se7en', keyword: 'movies like se7en', type: 'similar', movieTitle: 'Se7en' },
  { slug: 'movies-like-jumanji', keyword: 'movies like jumanji', type: 'similar', movieTitle: 'Jumanji: Welcome to the Jungle' },
  { slug: 'movies-like-donnie-darko', keyword: 'movies like donnie darko', type: 'similar', movieTitle: 'Donnie Darko' },
  { slug: 'movies-like-hereditary', keyword: 'movies like hereditary', type: 'similar', movieTitle: 'Hereditary' },
  { slug: 'movies-like-the-matrix', keyword: 'movies like the matrix', type: 'similar', movieTitle: 'The Matrix' },
  { slug: 'movies-like-gladiator', keyword: 'movies like gladiator', type: 'similar', movieTitle: 'Gladiator' },
  { slug: 'movies-like-sicario', keyword: 'movies like sicario', type: 'similar', movieTitle: 'Sicario' },
  { slug: 'movies-like-the-goonies', keyword: 'movies like the goonies', type: 'similar', movieTitle: 'The Goonies' },

  { slug: 'underrated-horror-movies', keyword: 'underrated horror movies', type: 'discover', hint: 'Well-reviewed horror films most people missed — high vote average, moderate-to-low vote counts.' },
  { slug: 'underrated-comedy-movies', keyword: 'underrated comedy movies', type: 'discover', hint: 'Well-reviewed comedies that flew under the radar — high vote average, moderate-to-low vote counts.' },
  { slug: 'underrated-sci-fi-movies', keyword: 'underrated sci fi movies', type: 'discover', hint: 'Well-reviewed science fiction films that never got a wide audience — high vote average, moderate-to-low vote counts.' },
  { slug: 'underrated-thriller-movies', keyword: 'underrated thriller movies', type: 'discover', hint: 'Well-reviewed thrillers most people missed — high vote average, moderate-to-low vote counts.' },
  { slug: 'underrated-80s-movies', keyword: 'underrated 80s movies', type: 'discover', hint: 'Well-reviewed 1980s films most people missed — released 1980-1989, high vote average, moderate vote counts.' },
  { slug: 'underrated-2000s-movies', keyword: 'underrated 2000s movies', type: 'discover', hint: 'Well-reviewed 2000s films that flew under the radar — released 2000-2009, high vote average, moderate vote counts.' },
  { slug: 'feel-good-comedy-movies', keyword: 'feel good comedy movies', type: 'discover', hint: 'Uplifting comedies — light, warm, rewatchable.' },
  { slug: 'romantic-movies-to-watch', keyword: 'romantic movies to watch', type: 'discover', hint: 'Great romance films — crowd-pleasing and well-reviewed.' },
  { slug: 'movies-to-watch-high', keyword: 'movies to watch high', type: 'discover', hint: 'Visually trippy or absurdly funny films — stoner-comedy keywords, surreal animated or psychedelic picks.' },
  { slug: 'scary-movies-to-watch', keyword: 'scary movies to watch', type: 'discover', hint: 'The scariest well-regarded horror films — horror genre with strong ratings.' },
  { slug: 'classic-movies-to-watch', keyword: 'classic movies to watch', type: 'discover', hint: 'Essential pre-1990 classics that still hold up — high vote average, high vote counts.' },
  { slug: 'mind-bending-horror-movies', keyword: 'mind bending horror movies', type: 'discover', hint: 'Horror films with psychological or reality-twisting angles — psychological-horror / surreal keywords where possible.' }
]
